import { useState } from "react";
import "./App.css";

const API_URL = "http://127.0.0.1:8000";

function App() {
  const [code, setCode] = useState("");
  const [result, setResult] = useState(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");

  const analyzeCode = async () => {
    if (!code.trim()) {
      setError("Please enter source code before analyzing.");
      setResult(null);
      return;
    }

    setLoading(true);
    setError("");
    setResult(null);

    try {
      const response = await fetch(`${API_URL}/api/predict`, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          code: code,
        }),
      });

      const data = await response.json();

      if (!response.ok) {
        throw new Error(
          data.detail || "Failed to analyze the source code."
        );
      }

      setResult(data);
    } catch (err) {
      setError(
        err.message ||
          "Unable to connect to the vulnerability detection API."
      );
    } finally {
      setLoading(false);
    }
  };

  const clearCode = () => {
    setCode("");
    setResult(null);
    setError("");
  };

  const loadExample = () => {
    setCode(`#include <stdio.h>
#include <string.h>

int main() {
    char buffer[10];
    char input[100];

    gets(input);
    strcpy(buffer, input);

    printf("%s", buffer);

    return 0;
}`);
    setResult(null);
    setError("");
  };

  const getResultClass = (label) => {
    if (label === "Vulnerable") {
      return "vulnerable";
    }

    if (label === "Safe") {
      return "safe";
    }

    return "uncertain";
  };

  const formatConfidence = (confidence) => {
    return `${(confidence * 100).toFixed(2)}%`;
  };

  return (
    <div className="app">

      {/* Header */}
      <header className="header">
        <div className="header-content">
          <div>
            <h1>Source Code Vulnerability Detector</h1>
            <p>
              Detect potential vulnerabilities using Random Forest
              and CNN machine learning models.
            </p>
          </div>

          <div className="status">
            <span className="status-dot"></span>
            ML API
          </div>
        </div>
      </header>


      {/* Main */}
      <main className="container">

        {/* Code Input Section */}
        <section className="card">

          <div className="section-header">
            <div>
              <h2>Source Code Analysis</h2>
              <p>
                Paste your C/C++ source code below and analyze it
                for potential vulnerabilities.
              </p>
            </div>

            <button
              className="example-button"
              onClick={loadExample}
            >
              Load Example
            </button>
          </div>


          <textarea
            className="code-editor"
            value={code}
            onChange={(e) => setCode(e.target.value)}
            placeholder="// Paste your source code here..."
            spellCheck="false"
          />


          <div className="editor-footer">

            <span className="character-count">
              {code.length} characters
            </span>

            <div className="actions">

              <button
                className="clear-button"
                onClick={clearCode}
              >
                Clear
              </button>

              <button
                className="analyze-button"
                onClick={analyzeCode}
                disabled={loading}
              >
                {loading ? "Analyzing..." : "Analyze Code"}
              </button>

            </div>
          </div>

        </section>


        {/* Error */}
        {error && (
          <div className="error-message">
            <strong>Error:</strong> {error}
          </div>
        )}


        {/* Results */}
        {result && (
          <section className="results-section">

            <div className="results-header">
              <div>
                <h2>Analysis Results</h2>
                <p>
                  Predictions generated by the trained machine
                  learning models.
                </p>
              </div>
            </div>


            {/* Overall Result */}
            <div
              className={`overall-result ${getResultClass(
                result.overall.label
              )}`}
            >
              <div>
                <span className="result-label">
                  Overall Result
                </span>

                <h3>{result.overall.label}</h3>
              </div>

              <div className="result-icon">
                {result.overall.label === "Vulnerable"
                  ? "!"
                  : result.overall.label === "Safe"
                  ? "✓"
                  : "?"}
              </div>
            </div>


            {/* Model Cards */}
            <div className="model-grid">

              {/* Random Forest */}
              <div className="model-card">

                <div className="model-card-header">
                  <div>
                    <span className="model-type">
                      Machine Learning
                    </span>

                    <h3>Random Forest</h3>
                  </div>

                  <span
                    className={`prediction-badge ${getResultClass(
                      result.random_forest.label
                    )}`}
                  >
                    {result.random_forest.label}
                  </span>
                </div>


                <div className="confidence">
                  <div className="confidence-header">
                    <span>Confidence</span>
                    <strong>
                      {formatConfidence(
                        result.random_forest.confidence
                      )}
                    </strong>
                  </div>

                  <div className="progress">
                    <div
                      className={`progress-bar ${getResultClass(
                        result.random_forest.label
                      )}`}
                      style={{
                        width: formatConfidence(
                          result.random_forest.confidence
                        ),
                      }}
                    ></div>
                  </div>
                </div>

              </div>


              {/* CNN */}
              <div className="model-card">

                <div className="model-card-header">
                  <div>
                    <span className="model-type">
                      Deep Learning
                    </span>

                    <h3>Convolutional Neural Network</h3>
                  </div>

                  <span
                    className={`prediction-badge ${getResultClass(
                      result.cnn.label
                    )}`}
                  >
                    {result.cnn.label}
                  </span>
                </div>


                <div className="confidence">
                  <div className="confidence-header">
                    <span>Confidence</span>
                    <strong>
                      {formatConfidence(
                        result.cnn.confidence
                      )}
                    </strong>
                  </div>

                  <div className="progress">
                    <div
                      className={`progress-bar ${getResultClass(
                        result.cnn.label
                      )}`}
                      style={{
                        width: formatConfidence(
                          result.cnn.confidence
                        ),
                      }}
                    ></div>
                  </div>
                </div>

              </div>

            </div>


            {/* Model Performance */}
            <div className="performance-card">

              <h2>Model Performance</h2>

              <div className="performance-grid">

                <div className="metric">
                  <span>Random Forest Accuracy</span>
                  <strong>74.51%</strong>
                </div>

                <div className="metric">
                  <span>CNN Accuracy</span>
                  <strong>77.48%</strong>
                </div>

                <div className="metric">
                  <span>Random Forest F1-Score</span>
                  <strong>67.53%</strong>
                </div>

                <div className="metric">
                  <span>CNN F1-Score</span>
                  <strong>69.00%</strong>
                </div>

              </div>

            </div>

          </section>
        )}


        {/* Information */}
        {!result && !loading && (
          <section className="information">

            <div className="info-card">
              <div className="info-icon">RF</div>

              <h3>Random Forest</h3>

              <p>
                A traditional machine learning model using
                TF-IDF feature extraction.
              </p>

              <strong>74.51% Accuracy</strong>
            </div>


            <div className="info-card">
              <div className="info-icon">CNN</div>

              <h3>CNN</h3>

              <p>
                A deep learning model that learns patterns
                from tokenized source code.
              </p>

              <strong>77.48% Accuracy</strong>
            </div>


            <div className="info-card">
              <div className="info-icon">AI</div>

              <h3>Dual Model Analysis</h3>

              <p>
                Predictions from both models are compared
                to provide an overall result.
              </p>

              <strong>Automated Detection</strong>
            </div>

          </section>
        )}

      </main>


      {/* Footer */}
      <footer className="footer">
        <p>
          NLP Project — Source Code Vulnerability Detection
        </p>
      </footer>

    </div>
  );
}

export default App;